strictness: high
doc-warnings: false
test-warnings: false
autodetect: true
member-warnings: false

ignore-patterns:
  - .*__init__.py$
  - snowshu/core/models/credentials.py  # raises "dodgy: password" which can not be silenced with noqa at prospector version 1.8.3

pylint:
  options:
    max-line-length: 120
  disable:
    - abstract-method
    - use-list-literal
    - logging-fstring-interpolation
    - cyclic-import # https://github.com/PyCQA/pylint/issues/3525

mccabe:
  disable:
    - MC0001  # at prospector version 1.8.3 noqa comments for mccabe errors are not respected
              # need to refactor those methods later

pyflakes:
  disable:
    - F821  # at prospector version 1.8.3 noqa comments for pyflakes errors are not respected
            # need to refactor those methods later

pycodestyle:
  options:
    max-line-length: 120
